version: '2'

services:

  web:
    build: .
    volumes:
      - ./src/:/var/www/html
      - ./data/logs:/var/log/apache2
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: ss
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  data:
    driver: local
    